kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-sample-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-sample-app
  template:
    metadata:
      labels:
        app: flask-sample-app
    spec:
      containers:
        - name: flask-sample-app
          image: docker.io/harshasridhar/flask-sample-app:v1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Always